# Generated by Django 3.1.5 on 2021-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeParkingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station_id', models.IntegerField()),
                ('start_station_name', models.CharField(max_length=70)),
                ('start_station_latitude', models.CharField(max_length=30)),
                ('start_station_longitude', models.CharField(max_length=30)),
                ('end_station_id', models.IntegerField()),
                ('end_station_name', models.CharField(max_length=70)),
                ('end_station_latitude', models.CharField(max_length=30)),
                ('end_station_longitude', models.CharField(max_length=30)),
            ],
        ),
    ]
