# Generated by Django 3.1.5 on 2021-03-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bikeparkinginfo',
            table='bike_parking_info',
        ),
    ]
