version: '3.2'

services:
  db:
    image: mysql:8.0
    ports:
      - '3302:3306'
    environment:
       MYSQL_DATABASE: 'motor_vehicle_collision'
       MYSQL_USER: 'creditshelf_user'
       MYSQL_PASSWORD: '12345678'
       MYSQL_ROOT_PASSWORD: '12345678'
    networks:
      - db-net

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/motor_vehicle_crash
    ports:
      - "5000:8000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command: npm start
    container_name: front
    build:
      context: ../../../react code/collision-UI/collision-info
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    stdin_open: true
    depends_on:
      - web
    networks:
      - db-net



networks:
      db-net:
        driver: bridge