# Generated by Django 3.1.5 on 2021-03-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=40)),
                ('cityUrl', models.CharField(max_length=300)),
                ('cityLinkForSoda', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CollisionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borough', models.CharField(max_length=20)),
                ('crashDate', models.DateTimeField()),
                ('crashTime', models.TimeField()),
                ('zipCode', models.IntegerField()),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('crossStreetName', models.CharField(max_length=30)),
                ('numberOfPersonsInjured', models.IntegerField(default=0)),
                ('numberOfPersonsKilled', models.IntegerField(default=0)),
                ('numberOfPedestriansInjured', models.IntegerField(default=0)),
                ('numberOfPedestriansKilled', models.IntegerField(default=0)),
                ('numberOfCyclistInjured', models.IntegerField(default=0)),
                ('numberOfCyclistKilled', models.IntegerField(default=0)),
                ('numberOfMotoristInjured', models.IntegerField(default=0)),
                ('numberOfMotoristKilled', models.IntegerField(default=0)),
                ('contributingFactorVehicle1', models.CharField(default='Unspecified', max_length=50)),
                ('contributingFactorVehicle2', models.CharField(default='Unspecified', max_length=50)),
                ('collisionId', models.IntegerField()),
                ('vehicleTypeCode1', models.CharField(default='Unspecified', max_length=50)),
                ('vehicleTypeCode2', models.CharField(default='Unspecified', max_length=50)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collision_data.city')),
            ],
        ),
    ]
