# Generated by Django 3.1.5 on 2021-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collision_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cityLinkForSoda',
            new_name='city_link_for_soda',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='cityName',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='cityUrl',
            new_name='city_url',
        ),
        migrations.RenameField(
            model_name='collisiondetails',
            old_name='cityId',
            new_name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='shortener_name_soda_link',
            field=models.CharField(default='', max_length=30),
        ),
    ]
