# Generated by Django 3.1.5 on 2021-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collision_data', '0002_auto_20210311_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='collisiondetails',
            name='offStreetName',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='collisiondetails',
            name='onStreetName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
